application: schedule-meister
version: 1
runtime: python27
api_version: 1
threadsafe: false 

handlers:
- url: /scraper
  script: py_files/scraper.py
  login: admin

- url: /deleter
  script: py_files/deleter.py
  login: admin

- url: /save
  script: py_files/save.py

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /.*
  script: schedulemeister.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
